import type { GetStaticProps, NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/home/home.module.scss";
import Link from "next/link";
import contents, { localesObjKeys } from "../locales";

import { useRouter } from "next/router";
import { ChangeEvent } from "react";

const Home: NextPage = () => {
    const { locale, locales, defaultLocale, asPath } = useRouter();
    const router = useRouter();
    const localeText = contents[locale as localesObjKeys];

    const changeLanguage = (e: ChangeEvent<HTMLSelectElement>) => {
        const locale = e.target.value;
        const path = locale + router.pathname;
        router.replace(path, path, { locale });
    };

    return (
        <div>
            <Head>
                <title>Super Giant Games</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <div className={styles.headerContainer}>
                    <Image priority={true} width={187} height={48} src="/assets/images/logo.png" />
                    <div className={styles.headerDivisor}>
                        <div className={styles.divisorDecorator}></div>
                    </div>
                    <select className={styles.selectLanguage} name="language" onChange={(e) => changeLanguage(e)}>
                        {locales?.map((locale, index) => (
                            <Link key={index} href={asPath} locale={locale}>
                                <option>{locale}</option>
                            </Link>
                        ))}
                    </select>
                </div>
            </header>
            <main>
                <div className={styles.bgVideoContainer}>
                    <video className={styles.bgVideo} autoPlay muted loop>
                        <source src="/assets/videos/clip-hades.mp4" type="video/mp4" />
                    </video>
                </div>
                <h1 className={styles.mainHomeTitle}>{localeText.title}</h1>
                <div className={styles.dividerContainer}>
                    <img src="/assets/images/divider.png" />
                </div>
                <div className={styles.callToAction}>
                    <button>{localeText.ctaButton}</button>
                </div>
                <div className={styles.usefulLinks}>
                    <a className={styles.link} href="">
                        {localeText.ctaMacButton}
                    </a>
                    <a className={styles.link} href="">
                        {localeText.ctaCreateAccount}
                    </a>
                </div>
            </main>
            <footer>
                <div className={styles.footerContainer}>
                    <div className={styles.ratingsLogo}>
                        <Image width={100} height={100} src="/assets/images/br-ratings-logo.png" />
                        <ul>
                            <li>{localeText.ratingsText1}</li>
                            <li>{localeText.ratingsText2}</li>
                            <li>{localeText.ratingsText3}</li>
                            <li>{localeText.ratingsText4}</li>
                            <li>{localeText.ratingsText5}</li>
                        </ul>
                    </div>
                    <select className={styles.selectLegal} name="language">
                        <option value="PT-BR">{localeText.legalSelectText}</option>
                    </select>
                </div>
                <div className={styles.copyright}>
                    <p>
                        {localeText.copyrightText1}{" "}
                        <a href="https://hcaptcha.com/privacy" target="_blank">
                            {localeText.copyrightText2}
                        </a>{" "}
                        {localeText.copyrightText3}{" "}
                        <a href="https://hcaptcha.com/terms" target="_blank">
                            {localeText.copyrightText4}
                        </a>{" "}
                        {localeText.copyrightText5}
                    </p>
                    <p>{localeText.copyrightText6}</p>
                </div>
            </footer>
        </div>
    );
};

export default Home;
